// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: protos/entity.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Enumeration of entity types
type Entitytype int32

const (
	Entitytype_TXN         Entitytype = 0
	Entitytype_BLOCK       Entitytype = 1
	Entitytype_MINERCONFIG Entitytype = 2
)

// Enum value maps for Entitytype.
var (
	Entitytype_name = map[int32]string{
		0: "TXN",
		1: "BLOCK",
		2: "MINERCONFIG",
	}
	Entitytype_value = map[string]int32{
		"TXN":         0,
		"BLOCK":       1,
		"MINERCONFIG": 2,
	}
)

func (x Entitytype) Enum() *Entitytype {
	p := new(Entitytype)
	*p = x
	return p
}

func (x Entitytype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Entitytype) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_entity_proto_enumTypes[0].Descriptor()
}

func (Entitytype) Type() protoreflect.EnumType {
	return &file_protos_entity_proto_enumTypes[0]
}

func (x Entitytype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Entitytype.Descriptor instead.
func (Entitytype) EnumDescriptor() ([]byte, []int) {
	return file_protos_entity_proto_rawDescGZIP(), []int{0}
}

// A message for Block entity data
type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Hash of the Block
	Blockhash []byte `protobuf:"bytes,1,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	// Data of the Block
	// Must decode to a weave.core.Block object
	Blockdata []byte `protobuf:"bytes,2,opt,name=blockdata,proto3" json:"blockdata,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_protos_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_protos_entity_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetBlockhash() []byte {
	if x != nil {
		return x.Blockhash
	}
	return nil
}

func (x *Block) GetBlockdata() []byte {
	if x != nil {
		return x.Blockdata
	}
	return nil
}

// A message for Transaction entity data
type Txn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Hash of the Transaction
	Txnhash []byte `protobuf:"bytes,1,opt,name=txnhash,proto3" json:"txnhash,omitempty"`
	// Data of the Transaction
	// Must decode to a weave.core.Transaction object
	Txndata []byte `protobuf:"bytes,2,opt,name=txndata,proto3" json:"txndata,omitempty"`
}

func (x *Txn) Reset() {
	*x = Txn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Txn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txn) ProtoMessage() {}

func (x *Txn) ProtoReflect() protoreflect.Message {
	mi := &file_protos_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txn.ProtoReflect.Descriptor instead.
func (*Txn) Descriptor() ([]byte, []int) {
	return file_protos_entity_proto_rawDescGZIP(), []int{1}
}

func (x *Txn) GetTxnhash() []byte {
	if x != nil {
		return x.Txnhash
	}
	return nil
}

func (x *Txn) GetTxndata() []byte {
	if x != nil {
		return x.Txndata
	}
	return nil
}

// A message for the miner configuration values
type MinerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Size of the miner transaction memory pool.
	// This value determines how many transactions included in a block.
	Poolsize uint32 `protobuf:"varint,1,opt,name=poolsize,proto3" json:"poolsize,omitempty"`
	// Difficulty of the proof-of-work algorithm.
	// This value determines the target number of leading zeros in a block hash.
	Difficulty uint32 `protobuf:"varint,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	// Reward for mining a block.
	// This value determines the reward for mining a block.
	Reward uint32 `protobuf:"varint,3,opt,name=reward,proto3" json:"reward,omitempty"`
}

func (x *MinerConfig) Reset() {
	*x = MinerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerConfig) ProtoMessage() {}

func (x *MinerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protos_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerConfig.ProtoReflect.Descriptor instead.
func (*MinerConfig) Descriptor() ([]byte, []int) {
	return file_protos_entity_proto_rawDescGZIP(), []int{2}
}

func (x *MinerConfig) GetPoolsize() uint32 {
	if x != nil {
		return x.Poolsize
	}
	return 0
}

func (x *MinerConfig) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *MinerConfig) GetReward() uint32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

// A message for an arbritary entity
type Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of the entity
	Type Entitytype `protobuf:"varint,1,opt,name=type,proto3,enum=Entitytype" json:"type,omitempty"`
	// Data of the entity
	//
	// Types that are assignable to Entity:
	//	*Entity_Block
	//	*Entity_Txn
	//	*Entity_Minerconfig
	Entity isEntity_Entity `protobuf_oneof:"entity"`
}

func (x *Entity) Reset() {
	*x = Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_entity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_protos_entity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_protos_entity_proto_rawDescGZIP(), []int{3}
}

func (x *Entity) GetType() Entitytype {
	if x != nil {
		return x.Type
	}
	return Entitytype_TXN
}

func (m *Entity) GetEntity() isEntity_Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (x *Entity) GetBlock() *Block {
	if x, ok := x.GetEntity().(*Entity_Block); ok {
		return x.Block
	}
	return nil
}

func (x *Entity) GetTxn() *Txn {
	if x, ok := x.GetEntity().(*Entity_Txn); ok {
		return x.Txn
	}
	return nil
}

func (x *Entity) GetMinerconfig() *MinerConfig {
	if x, ok := x.GetEntity().(*Entity_Minerconfig); ok {
		return x.Minerconfig
	}
	return nil
}

type isEntity_Entity interface {
	isEntity_Entity()
}

type Entity_Block struct {
	// Type must be BLOCK
	Block *Block `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

type Entity_Txn struct {
	// Type must be TXN
	Txn *Txn `protobuf:"bytes,3,opt,name=txn,proto3,oneof"`
}

type Entity_Minerconfig struct {
	// Type must be MINERCONFIG
	Minerconfig *MinerConfig `protobuf:"bytes,4,opt,name=minerconfig,proto3,oneof"`
}

func (*Entity_Block) isEntity_Entity() {}

func (*Entity_Txn) isEntity_Entity() {}

func (*Entity_Minerconfig) isEntity_Entity() {}

var File_protos_entity_proto protoreflect.FileDescriptor

var file_protos_entity_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1c,
	0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x03, 0x54, 0x78,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x6e, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x74, 0x78, 0x6e, 0x68, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x78, 0x6e, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x78,
	0x6e, 0x64, 0x61, 0x74, 0x61, 0x22, 0x61, 0x0a, 0x0b, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x06, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x74, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x03, 0x74, 0x78, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x04, 0x2e, 0x54, 0x78, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x74, 0x78, 0x6e, 0x12, 0x30,
	0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x48, 0x00, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x42, 0x08, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2a, 0x31, 0x0a, 0x0a, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x74, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x58, 0x4e, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x4d, 0x49, 0x4e, 0x45, 0x52, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0x02, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_entity_proto_rawDescOnce sync.Once
	file_protos_entity_proto_rawDescData = file_protos_entity_proto_rawDesc
)

func file_protos_entity_proto_rawDescGZIP() []byte {
	file_protos_entity_proto_rawDescOnce.Do(func() {
		file_protos_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_entity_proto_rawDescData)
	})
	return file_protos_entity_proto_rawDescData
}

var file_protos_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_entity_proto_goTypes = []interface{}{
	(Entitytype)(0),     // 0: entitytype
	(*Block)(nil),       // 1: Block
	(*Txn)(nil),         // 2: Txn
	(*MinerConfig)(nil), // 3: MinerConfig
	(*Entity)(nil),      // 4: Entity
}
var file_protos_entity_proto_depIdxs = []int32{
	0, // 0: Entity.type:type_name -> entitytype
	1, // 1: Entity.block:type_name -> Block
	2, // 2: Entity.txn:type_name -> Txn
	3, // 3: Entity.minerconfig:type_name -> MinerConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_entity_proto_init() }
func file_protos_entity_proto_init() {
	if File_protos_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Txn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_entity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_entity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_entity_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Entity_Block)(nil),
		(*Entity_Txn)(nil),
		(*Entity_Minerconfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_entity_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_entity_proto_goTypes,
		DependencyIndexes: file_protos_entity_proto_depIdxs,
		EnumInfos:         file_protos_entity_proto_enumTypes,
		MessageInfos:      file_protos_entity_proto_msgTypes,
	}.Build()
	File_protos_entity_proto = out.File
	file_protos_entity_proto_rawDesc = nil
	file_protos_entity_proto_goTypes = nil
	file_protos_entity_proto_depIdxs = nil
}
