// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: protos/response.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Enumeration of response types
type ResponseResponsetype int32

const (
	Response_TXN       ResponseResponsetype = 0
	Response_BLOCK     ResponseResponsetype = 1
	Response_STATE     ResponseResponsetype = 2
	Response_STATUS    ResponseResponsetype = 3
	Response_INVENTORY ResponseResponsetype = 4
)

// Enum value maps for ResponseResponsetype.
var (
	ResponseResponsetype_name = map[int32]string{
		0: "TXN",
		1: "BLOCK",
		2: "STATE",
		3: "STATUS",
		4: "INVENTORY",
	}
	ResponseResponsetype_value = map[string]int32{
		"TXN":       0,
		"BLOCK":     1,
		"STATE":     2,
		"STATUS":    3,
		"INVENTORY": 4,
	}
)

func (x ResponseResponsetype) Enum() *ResponseResponsetype {
	p := new(ResponseResponsetype)
	*p = x
	return p
}

func (x ResponseResponsetype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseResponsetype) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_response_proto_enumTypes[0].Descriptor()
}

func (ResponseResponsetype) Type() protoreflect.EnumType {
	return &file_protos_response_proto_enumTypes[0]
}

func (x ResponseResponsetype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseResponsetype.Descriptor instead.
func (ResponseResponsetype) EnumDescriptor() ([]byte, []int) {
	return file_protos_response_proto_rawDescGZIP(), []int{5, 0}
}

// A message for a Block query response
type BlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Response block data
	Block *Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_protos_response_proto_rawDescGZIP(), []int{0}
}

func (x *BlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// A message for a Transaction query response
type TxnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Response transaction data
	Txn *Txn `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
}

func (x *TxnResponse) Reset() {
	*x = TxnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnResponse) ProtoMessage() {}

func (x *TxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnResponse.ProtoReflect.Descriptor instead.
func (*TxnResponse) Descriptor() ([]byte, []int) {
	return file_protos_response_proto_rawDescGZIP(), []int{1}
}

func (x *TxnResponse) GetTxn() *Txn {
	if x != nil {
		return x.Txn
	}
	return nil
}

// A message for a State query response
type StateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Height of the chain on the peer that sent the response
	Chainheight uint32 `protobuf:"varint,1,opt,name=chainheight,proto3" json:"chainheight,omitempty"`
	// Miner configuration state of the peer that sent the response
	Minerconfig *MinerConfig `protobuf:"bytes,2,opt,name=minerconfig,proto3" json:"minerconfig,omitempty"`
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_protos_response_proto_rawDescGZIP(), []int{2}
}

func (x *StateResponse) GetChainheight() uint32 {
	if x != nil {
		return x.Chainheight
	}
	return 0
}

func (x *StateResponse) GetMinerconfig() *MinerConfig {
	if x != nil {
		return x.Minerconfig
	}
	return nil
}

// A message for an Inventory query response
type InventoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of blocks on the chain of the peer that sent the response.
	// The included blocks are from the highest block on the peer's chain
	// upto the last block available on the requesting peer (taken from query).
	Chainblocks []*Block `protobuf:"bytes,1,rep,name=chainblocks,proto3" json:"chainblocks,omitempty"`
	// List of transactions in the mempool of the peer that sent the response. The transactions
	// are included based on if the requesting peer has asked for it (taken from query).
	Pooltxns []*Txn `protobuf:"bytes,2,rep,name=pooltxns,proto3" json:"pooltxns,omitempty"`
}

func (x *InventoryResponse) Reset() {
	*x = InventoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_response_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResponse) ProtoMessage() {}

func (x *InventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_response_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResponse.ProtoReflect.Descriptor instead.
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_response_proto_rawDescGZIP(), []int{3}
}

func (x *InventoryResponse) GetChainblocks() []*Block {
	if x != nil {
		return x.Chainblocks
	}
	return nil
}

func (x *InventoryResponse) GetPooltxns() []*Txn {
	if x != nil {
		return x.Pooltxns
	}
	return nil
}

// A message for a Status query response
type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of entity for which status is being returned
	Type Entitytype `protobuf:"varint,1,opt,name=type,proto3,enum=Entitytype" json:"type,omitempty"`
	// Hash of the entity for which status is being returned
	Entityhash []byte `protobuf:"bytes,2,opt,name=entityhash,proto3" json:"entityhash,omitempty"`
	// Status of the entity
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_response_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_response_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_response_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetType() Entitytype {
	if x != nil {
		return x.Type
	}
	return Entitytype_TXN
}

func (x *StatusResponse) GetEntityhash() []byte {
	if x != nil {
		return x.Entityhash
	}
	return nil
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// A message for an arbitrary query response
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of response
	Type ResponseResponsetype `protobuf:"varint,1,opt,name=type,proto3,enum=ResponseResponsetype" json:"type,omitempty"`
	// Body of response
	//
	// Types that are assignable to Body:
	//	*Response_Txnresponse
	//	*Response_Blockresponse
	//	*Response_Stateresponse
	//	*Response_Statusresponse
	//	*Response_Inventoryresponse
	Body isResponse_Body `protobuf_oneof:"body"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_response_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_response_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_response_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetType() ResponseResponsetype {
	if x != nil {
		return x.Type
	}
	return Response_TXN
}

func (m *Response) GetBody() isResponse_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Response) GetTxnresponse() *TxnResponse {
	if x, ok := x.GetBody().(*Response_Txnresponse); ok {
		return x.Txnresponse
	}
	return nil
}

func (x *Response) GetBlockresponse() *BlockResponse {
	if x, ok := x.GetBody().(*Response_Blockresponse); ok {
		return x.Blockresponse
	}
	return nil
}

func (x *Response) GetStateresponse() *StateResponse {
	if x, ok := x.GetBody().(*Response_Stateresponse); ok {
		return x.Stateresponse
	}
	return nil
}

func (x *Response) GetStatusresponse() *StatusResponse {
	if x, ok := x.GetBody().(*Response_Statusresponse); ok {
		return x.Statusresponse
	}
	return nil
}

func (x *Response) GetInventoryresponse() *InventoryResponse {
	if x, ok := x.GetBody().(*Response_Inventoryresponse); ok {
		return x.Inventoryresponse
	}
	return nil
}

type isResponse_Body interface {
	isResponse_Body()
}

type Response_Txnresponse struct {
	// Type must be TXN
	Txnresponse *TxnResponse `protobuf:"bytes,2,opt,name=txnresponse,proto3,oneof"`
}

type Response_Blockresponse struct {
	// Type must be BLOCK
	Blockresponse *BlockResponse `protobuf:"bytes,3,opt,name=blockresponse,proto3,oneof"`
}

type Response_Stateresponse struct {
	// Type must be STATE
	Stateresponse *StateResponse `protobuf:"bytes,4,opt,name=stateresponse,proto3,oneof"`
}

type Response_Statusresponse struct {
	// Type must be STATUS
	Statusresponse *StatusResponse `protobuf:"bytes,5,opt,name=statusresponse,proto3,oneof"`
}

type Response_Inventoryresponse struct {
	// Type must be INVENTORY
	Inventoryresponse *InventoryResponse `protobuf:"bytes,6,opt,name=inventoryresponse,proto3,oneof"`
}

func (*Response_Txnresponse) isResponse_Body() {}

func (*Response_Blockresponse) isResponse_Body() {}

func (*Response_Stateresponse) isResponse_Body() {}

func (*Response_Statusresponse) isResponse_Body() {}

func (*Response_Inventoryresponse) isResponse_Body() {}

var File_protos_response_proto protoreflect.FileDescriptor

var file_protos_response_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0d,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x25, 0x0a, 0x0b, 0x54,
	0x78, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x74, 0x78,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x03, 0x74,
	0x78, 0x6e, 0x22, 0x61, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4d, 0x69, 0x6e,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x5f, 0x0a, 0x11, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x0b, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x12, 0x20, 0x0a, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x74, 0x78, 0x6e, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x08, 0x70, 0x6f,
	0x6f, 0x6c, 0x74, 0x78, 0x6e, 0x73, 0x22, 0x69, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x74,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0xa9, 0x03, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x74, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x74, 0x78,
	0x6e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x0b, 0x74, 0x78, 0x6e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0d,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0e,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x11, 0x69, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x11, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x48, 0x0a, 0x0c, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x54,
	0x58, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54,
	0x4f, 0x52, 0x59, 0x10, 0x04, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_response_proto_rawDescOnce sync.Once
	file_protos_response_proto_rawDescData = file_protos_response_proto_rawDesc
)

func file_protos_response_proto_rawDescGZIP() []byte {
	file_protos_response_proto_rawDescOnce.Do(func() {
		file_protos_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_response_proto_rawDescData)
	})
	return file_protos_response_proto_rawDescData
}

var file_protos_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_response_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_response_proto_goTypes = []interface{}{
	(ResponseResponsetype)(0), // 0: Response.responsetype
	(*BlockResponse)(nil),     // 1: BlockResponse
	(*TxnResponse)(nil),       // 2: TxnResponse
	(*StateResponse)(nil),     // 3: StateResponse
	(*InventoryResponse)(nil), // 4: InventoryResponse
	(*StatusResponse)(nil),    // 5: StatusResponse
	(*Response)(nil),          // 6: Response
	(*Block)(nil),             // 7: Block
	(*Txn)(nil),               // 8: Txn
	(*MinerConfig)(nil),       // 9: MinerConfig
	(Entitytype)(0),           // 10: entitytype
}
var file_protos_response_proto_depIdxs = []int32{
	7,  // 0: BlockResponse.block:type_name -> Block
	8,  // 1: TxnResponse.txn:type_name -> Txn
	9,  // 2: StateResponse.minerconfig:type_name -> MinerConfig
	7,  // 3: InventoryResponse.chainblocks:type_name -> Block
	8,  // 4: InventoryResponse.pooltxns:type_name -> Txn
	10, // 5: StatusResponse.type:type_name -> entitytype
	0,  // 6: Response.type:type_name -> Response.responsetype
	2,  // 7: Response.txnresponse:type_name -> TxnResponse
	1,  // 8: Response.blockresponse:type_name -> BlockResponse
	3,  // 9: Response.stateresponse:type_name -> StateResponse
	5,  // 10: Response.statusresponse:type_name -> StatusResponse
	4,  // 11: Response.inventoryresponse:type_name -> InventoryResponse
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_protos_response_proto_init() }
func file_protos_response_proto_init() {
	if File_protos_response_proto != nil {
		return
	}
	file_protos_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_response_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InventoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_response_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_response_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_response_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Response_Txnresponse)(nil),
		(*Response_Blockresponse)(nil),
		(*Response_Stateresponse)(nil),
		(*Response_Statusresponse)(nil),
		(*Response_Inventoryresponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_response_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_response_proto_goTypes,
		DependencyIndexes: file_protos_response_proto_depIdxs,
		EnumInfos:         file_protos_response_proto_enumTypes,
		MessageInfos:      file_protos_response_proto_msgTypes,
	}.Build()
	File_protos_response_proto = out.File
	file_protos_response_proto_rawDesc = nil
	file_protos_response_proto_goTypes = nil
	file_protos_response_proto_depIdxs = nil
}
